### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by matthew-piziak** [sigma/pcache#11]
```
(let ((repo (pcache-repository "plop")))
  (pcache-put repo 'foo 42) ; store value 42 with key 'foo
  (pcache-get repo 'foo) ; => 42
  )
```

Evaluating this results in `Obsolete name arg "plop" to constructor pcache-repository`.

**Comment by sergeyklay** [comment]
Looks loks this is related to https://github.com/sigma/pcache/pull/5

**Comment by sigma** [comment]
pcache has been modernized wrt eieio, so it should work as advertized, and without warnings

**Comment by matthew-piziak** [comment]
@sigma Confirmed on my machine. Thank you!

**Comment by sergeyklay** [comment]
Yay! Thank you!
